spring:
  data:
    mongodb:
      uri: mongodb://xubi:Aa123456@200.22.242.46:27017/xubi
  redis:
    #数据库索引
    database: 0
    host: 113.62.180.64
    port: 6379
    password: Fullsee@123
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000